# Gradient Descent
In this...we calculate the value of m and c

In [7]:
import numpy as np

In [10]:
import pandas as pd
data = pd.read_csv("Datasets/19_420_bundle_archive/Iris.csv")
data
np_data = data.reset_index().values

In [28]:
np_data = np.delete(np_data,2,axis = 1)
np_data

array([[5.1, 3.5],
       [4.9, 3.0],
       [4.7, 3.2],
       [4.6, 3.1],
       [5.0, 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5.0, 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3.0],
       [4.3, 3.0],
       [5.8, 4.0],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5.0, 3.0],
       [5.0, 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5.0, 3.2],
       [5.5, 3.5],
       [4.9, 3.1],
       [4.4, 3.0],
       [5.1, 3.4],
       [5.0, 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5.0, 3.5],
       [5.1, 3.8],
       [4.8, 3.0],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5.0, 3.3],
       [7.0, 3.2],
       [6.4, 3.2],
       [6.9,

In [29]:
np_data.shape

(150, 2)

# Gradient Descent Code

In [30]:
def step_gradient(points,learning_rate,m,c):
    m_slope = 0
    c_slope = 0
    M = len(points)
    for i in range(M):
        x = points[i,0]
        y = points[i,1]
        m_slope = (-2/M)*(y-m*x - c)*x
        c_slope = (-2/M)*(y-m*x - c)
    new_m = m - learning_rate*m_slope
    new_c = c - learning_rate*c_slope
    return new_m,new_c

In [31]:
def gd(points,learning_rate,num_iterations):
    m = 0
    c = 0
    for i in range(num_iterations):
        m,c = step_gradient(points,learning_rate,m,c)
    return m,c

In [32]:
def run():
    learning_rate = 0.001
    num_iterations = 100
    m,c = gd(np_data,learning_rate,num_iterations)
    print(m,c)

In [33]:
run()

0.023050823402899993 0.003906919220830507


# Feature Scaling
It is done as a part of preprocessing so that any single feature doesnot dominate the whole result

In [35]:
from sklearn import preprocessing

In [36]:
X = np.array([[1,-1,2],
             [2,0,0],
             [0,1,-1]])

In [39]:
#it simply scale the data
X_scaled = preprocessing.scale(X)

In [40]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [43]:
print(X_scale.mean(axis = 0))
print(X_scaled.std(axis = 0))

[0. 0. 0.]
[1. 1. 1.]


In [46]:
#it also store the parameter on which the scaling is done
scaler = preprocessing.StandardScaler()
#to store parameter
scaler.fit(X)
#to transform data
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [47]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])