#Linear Regression Implementation

In [74]:
import pandas as pd

In [75]:
data = pd.read_csv("Datasets/19_420_bundle_archive/Iris.csv")
data
np_data = data.reset_index().values

In [93]:
np_data

array([[0, 1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [1, 2, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [2, 3, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [3, 4, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [4, 5, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5, 6, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [6, 7, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [7, 8, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [8, 9, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [9, 10, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [10, 11, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [11, 12, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [12, 13, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [13, 14, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [14, 15, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [15, 16, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [16, 17, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [17, 18, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [18, 19, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [19, 20, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [20, 21, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [21, 22, 3.7, 1.5, 0.4, '

In [99]:
np_data = np.delete(np_data,2,axis = 1)
np_data

array([[3.5, 1.4],
       [3.0, 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7],
       [3.4, 1.4],
       [3.4, 1.5],
       [2.9, 1.4],
       [3.1, 1.5],
       [3.7, 1.5],
       [3.4, 1.6],
       [3.0, 1.4],
       [3.0, 1.1],
       [4.0, 1.2],
       [4.4, 1.5],
       [3.9, 1.3],
       [3.5, 1.4],
       [3.8, 1.7],
       [3.8, 1.5],
       [3.4, 1.7],
       [3.7, 1.5],
       [3.6, 1.0],
       [3.3, 1.7],
       [3.4, 1.9],
       [3.0, 1.6],
       [3.4, 1.6],
       [3.5, 1.5],
       [3.4, 1.4],
       [3.2, 1.6],
       [3.1, 1.6],
       [3.4, 1.5],
       [4.1, 1.5],
       [4.2, 1.4],
       [3.1, 1.5],
       [3.2, 1.2],
       [3.5, 1.3],
       [3.1, 1.5],
       [3.0, 1.3],
       [3.4, 1.5],
       [3.5, 1.3],
       [2.3, 1.3],
       [3.2, 1.3],
       [3.5, 1.6],
       [3.8, 1.9],
       [3.0, 1.4],
       [3.8, 1.6],
       [3.2, 1.4],
       [3.7, 1.5],
       [3.3, 1.4],
       [3.2, 4.7],
       [3.2, 4.5],
       [3.1,

In [113]:
x=np_data[:,0]
x

array([3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0,
       3.0, 4.0, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.0,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3.0,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3.0, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2.0, 3.0, 2.2, 2.9, 2.9,
       3.1, 3.0, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3.0, 2.8, 3.0,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3.0, 3.4, 3.1, 2.3, 3.0, 2.5, 2.6,
       3.0, 2.6, 2.3, 2.7, 3.0, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3.0, 2.9,
       3.0, 3.0, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3.0, 2.5, 2.8, 3.2, 3.0,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3.0, 2.8, 3.0,
       2.8, 3.8, 2.8, 2.8, 2.6, 3.0, 3.4, 3.1, 3.0, 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3.0, 2.5, 3.0, 3.4, 3.0], dtype=object)

In [114]:
y=np_data[:,1]
y

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4,
       4.6, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1, 6.0, 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.0, 5.1, 5.3, 5.5,
       6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1], dtype=object)

In [115]:
x,y

(array([3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0,
        3.0, 4.0, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3.0,
        3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3.0,
        3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3.0, 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
        3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2.0, 3.0, 2.2, 2.9, 2.9,
        3.1, 3.0, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3.0, 2.8, 3.0,
        2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3.0, 3.4, 3.1, 2.3, 3.0, 2.5, 2.6,
        3.0, 2.6, 2.3, 2.7, 3.0, 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3.0, 2.9,
        3.0, 3.0, 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3.0, 2.5, 2.8, 3.2, 3.0,
        3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3.0, 2.8, 3.0,
        2.8, 3.8, 2.8, 2.8, 2.6, 3.0, 3.4, 3.1, 3.0, 3.1, 3.1, 3.1, 2.7,
        3.2, 3.3, 3.0, 2.5, 3.0, 3.4, 3.0], dtype=object),
 array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
        1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.

In [116]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(x,y , test_size=0.3)

In [117]:
X_train.shape

(105,)

In [118]:
Y_train.shape

(105,)

In [119]:
def fit(x_train,y_train):
    num = (x_train*y_train).mean() - x_train.mean() * y_train.mean()
    dem = (x_train**2).mean() - x_train.mean()**2
    m = num/dem
    c=y_train.mean() - m * x_train.mean()
    return m,c

In [120]:
def predict(x,m,c):
    return m * x + c

def score(y_truth,y_pred):
    u = ((y_truth - y_pred)**2).sum()
    v = ((y_truth - y_truth.mean())**2).sum()
    return 1-u/v
def cost(x,y,m,c):
    return ((y-m*x - c)**2).mean()

In [121]:
m,c = fit(X_train,Y_train)
print(m,c)
#test data
y_test_pred = predict(X_test,m,c)
print("Test Score",score(Y_test,y_test_pred))

#train data
y_train_pred = predict(X_train,m,c)
print("Train Score",score(Y_train,y_train_pred))
print("M,C",m,c)
print("Cost of training data",cost(X_train,Y_train,m,c))

-2.024165812440753 9.78324104499784
Test Score -0.10120384027464535
Train Score 0.2546668704689474
M,C -2.024165812440753 9.78324104499784
Cost of training data 2.2706558580283325


#sklearn

In [127]:
x=np_data[:,0].reshape(-1,1)
X_train = X_train.reshape(-1,1)

In [129]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg1.fit(X_train,Y_train)
print(alg1.intercept_)
print(alg1.coef_)

9.783241044997746
[-2.02416581]
